db.url=jdbc:mysql://localhost:3306/connectjdbc
db.username=root
db.password=Cisco@456
db.driver=com.mysql.cj.jdbc.Driver
db.port=3306

-- property file create -db.properties
-- connect with DBProperty
-- Dbproperty --> DBconn